version: '3.8'

services:
  ml-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ids-ml-api
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      # Configuration API
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - API_TITLE=${API_TITLE:-Système de Détection d'Intrusion Temps Réel}
      - API_VERSION=${API_VERSION:-1.0.0}

      # Configuration des seuils
      - DETECTION_THRESHOLD=${DETECTION_THRESHOLD:-0.5}
      - CONFIDENCE_THRESHOLD=${CONFIDENCE_THRESHOLD:-0.7}

      # Configuration des modèles ML
      - KNN_MODEL_WEIGHT=${KNN_MODEL_WEIGHT:-0.3}
      - MLP_MODEL_WEIGHT=${MLP_MODEL_WEIGHT:-0.35}
      - XGB_MODEL_WEIGHT=${XGB_MODEL_WEIGHT:-0.35}

      # Configuration du logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-%(asctime)s - %(name)s - %(levelname)s - %(message)s}

      # Configuration des alertes
      - ALERT_ENABLE_LOGGING=${ALERT_ENABLE_LOGGING:-true}
      - ALERT_ENABLE_WEBHOOKS=${ALERT_ENABLE_WEBHOOKS:-false}
      - ALERT_WEBHOOK_URL=${ALERT_WEBHOOK_URL:-}
      - ALERT_LOG_FILE=${ALERT_LOG_FILE:-alerts.log}
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    networks:
      - ids-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT:-8000}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ids-network:
    external: true
